Repository GoblinDBRocks/GoblinDB, pull requests merged in 2018-03, with the labels that each got.

#42 Database. Use '/' (or anything else) instead of '.' to navigate throu…
  .gitignore
  config.js
  demo/fear_the_goblin.js
  index.js
  lib/database.js
  test/goblin.js
Labels: enhancement, invalid

#44 Add Test cases for events
  lib/ambush.js
  lib/database.js
  lib/goblin.js
  lib/logger/index.js
  test/goblin.js
Labels: enhancement

#46 Error messages referencing FAQ. Closes #14
  lib/logger/index.js
Labels: enhancement

#48 Update package json to add Santi, Andrés and Alvaro as core contributors <3
  package.json
Labels: News

#49 v0.0.11 Meigas
  .gitignore
  README.md
  config.js
  demo/fear_the_goblin.js
  index.js
  lib/ambush.js
  lib/database.js
  lib/goblin.js
  lib/logger/index.js
  package.json
  test/goblin.js
Labels: enhancement
